// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_MVC.Data;

namespace Projeto_MVC.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201127031223_InitialMigration")]
    partial class InitialMigration 
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto_MVC.Models.AnimalModel", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("EspecieId");

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.Property<string>("Pedigree")
                        .HasMaxLength(50);

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ProprietarioId");

                    b.Property<decimal>("altura")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("AnimalId");

                    b.HasIndex("EspecieId");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Projeto_MVC.Models.EspecieModel", b =>
                {
                    b.Property<int>("EspecieId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.HasKey("EspecieId");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("Projeto_MVC.Models.ProprietarioModel", b =>
                {
                    b.Property<int>("ProprietarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade")
                        .HasMaxLength(50);

                    b.Property<string>("Cpf")
                        .HasMaxLength(14);

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.Property<string>("Rg")
                        .HasMaxLength(12);

                    b.Property<string>("Rua")
                        .HasMaxLength(50);

                    b.HasKey("ProprietarioId");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("Projeto_MVC.Models.AnimalModel", b =>
                {
                    b.HasOne("Projeto_MVC.Models.EspecieModel", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Projeto_MVC.Models.ProprietarioModel", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
